---
- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: true
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Install Gitlab
  apt:
    name: "gitlab-ce"
    state: latest
  environtment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"
  async: 300
  poll: 5
  when: not gitlab_file.stat.exists
