---
- name: Install package for gitlab
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - tzdata
    - perl
    - postfix
    - gnupg2

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: enabled
    enabled: true