---
- name: Install package for gitlab
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - tzdata
    - perl
    - postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: started
    enabled: true
