---
- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow http
  ufw:
    rule: allow
    port: '80'
    protocol: tcp

- name: Allow https
  ufw:
    rule: allow
    port: '443'
    protocol: tcp